server:
  port: 8081

spring:
  application:
    name: configclient
  config:
    #import: optional:configserver:http://localhost:8888/
    import: optional:configserver:http://config-server:8888/
  #cloud:
   # config:
    #  uri: http://localhost:8888  # URL of the Config Server
     # fail-fast: true             # Fail the startup if config server is not reachable

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
eureka: #this one is registering productservice to eureka server
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka 
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    root: INFO

