server:
  port: 8081

spring:
  application:
    name: configclient
  config:
    #import: http://config-server:8888/
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: false             # Fail the startup if config server is not reachable

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
eureka: #this one is registering productservice to eureka server
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO

info:
  environment: "default-env"