server:
  port: 8071

spring:
  application:
    name: userservice

#  zipkin:
#    base-url: http://zipkin:9411/
#  sleuth:
#    sampler:
#     probability: 1.0

eureka:
  client:
    service-url:
     #defaultZone: http://localhost:8761/eureka/
     defaultZone: http://eureka-server:8761/eureka/


management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # 100% tracing, adjust as needed
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans


logging:
  pattern:
   level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
