server:
  port: 8071

spring:
  application:
    name: userservice

#  zipkin:
#    base-url: http://zipkin:9411/
#  sleuth:
#    sampler:
#     probability: 1.0

eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
     #defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: localhost

#management:
#  tracing:
#    enabled: true
#    sampling:
#      probability: 1.0  # 100% tracing, adjust as needed
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/


logging:
  pattern:
   level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
